# fly.toml app configuration file generated for nudgeapp on 2024-11-04T16:23:35-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nudgeapp"
primary_region = "ord"
kill_signal = "SIGTERM"

[build]

[env]
  DB_PATH = "/data/local.db"
  HOST = "localhost"
  NODE_ENV = "production"
  PORT = "8080"
  PUBLIC_URL = "https://nudgeapp.fly.dev"

[mounts]
  source = "nudgeapp_data"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  min_machines_running = 0